blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://linefusion.io/discord
    about: Please ask and answer questions here.
  - name: Security Issues
    url: https://linefusion.io/security
    about: Please report security vulnerabilities here.
