name: Feature Request
description: Submit a feature request
title: "Feature: "
labels: ["feature"]
assignees: ["wolfulus"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request.
        Please make sure that there aren't any open/closed issues with the same (or similar) subject.
        
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: Detail as much as possible what you need and how do you expect it to work.
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Workarounds
      description: | 
        If you already have a workaround or implementations, please provide them so we can better decide how to implement it.
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information if you want.
